package org.openjfx.interop.generator;

import org.openjfx.interop.Kind;
import org.openjfx.interop.Layout;
import org.openjfx.interop.NativeSignatureEntry;
import org.openjfx.interop.Signature;
import org.openjfx.interop.annotations.NativeHeader;

import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Reads a {@link NativeSignatureEntry} enum's real constants (each one already a
 * bound {@code (symbol, Signature)} pair -- no per-field annotation needed, the enum
 * constant itself is the entry) and emits the {@link NativeHeader}-named
 * {@code extern "C"} header for it -- named-type declarations first (struct
 * typedefs from any referenced {@code Kind}'s {@link Layout.Struct}, function-pointer
 * typedefs from any {@link Layout.FunctionPointer}), then one prototype per entry.
 * Every {@code Kind} encountered must come from a class in {@code vettedKindClasses}
 * (i.e. {@code @NativeKindSet}-annotated) -- an un-vetted {@code Kind} fails the
 * generation loudly rather than silently making it into a header.
 */
public final class HeaderGenerator {

    private HeaderGenerator() {}

    public static void generate(Class<?> owner, Path outputDir, Set<Class<?>> vettedKindClasses) throws IOException {
        NativeHeader header = owner.getAnnotation(NativeHeader.class);
        if (header == null) {
            return;
        }

        Object[] constants = owner.getEnumConstants();
        if (constants == null || constants.length == 0) {
            return;
        }

        Set<Layout> namedTypes = new LinkedHashSet<>();
        List<String> prototypes = new ArrayList<>();

        for (Object constant : constants) {
            NativeSignatureEntry entry = (NativeSignatureEntry) constant;
            Signature signature = entry.signature();

            Kind result = requireVetted(signature.returnKind(), owner, vettedKindClasses);
            collectNamedType(result, namedTypes);
            StringBuilder params = new StringBuilder();
            Kind[] paramKinds = signature.paramKinds();
            for (int i = 0; i < paramKinds.length; i++) {
                Kind paramKind = requireVetted(paramKinds[i], owner, vettedKindClasses);
                collectNamedType(paramKind, namedTypes);
                if (i > 0) {
                    params.append(", ");
                }
                params.append(cType(paramKind)).append(" p").append(i);
            }
            prototypes.add(cType(result) + " " + entry.symbol() + "(" + params + ");");
        }

        Files.createDirectories(outputDir);
        Path outputFile = outputDir.resolve(header.value() + ".hj");
        try (Writer w = Files.newBufferedWriter(outputFile)) {
            w.write("// GENERATED by " + HeaderGenerator.class.getName()
                    + " from " + owner.getName() + "'s NativeSignatureEntry constants -- do not hand-edit.\n");
            w.write("#pragma once\n\n");
            // Self-contained per what @NativeHeader.includes() declares -- e.g.
            // <stdint.h> for a header using int32_t/int64_t -- rather than the
            // generator guessing or unconditionally emitting includes a given header
            // may not need. Never rely on the consuming .c file's own #include order
            // to supply this first, the way tier3_CharacterData.c's original
            // hand-written include order (this header before <cstdint>) silently did.
            for (String include : header.includes()) {
                w.write("#include " + include + "\n");
            }
            if (header.includes().length > 0) {
                w.write("\n");
            }
            for (Layout layout : namedTypes) {
                if (layout instanceof Layout.Struct s) {
                    for (String typedef : s.typedefs()) {
                        w.write(typedef);
                        w.write('\n');
                    }
                    w.write("typedef struct {\n");
                    for (Layout.Field f : s.fields()) {
                        w.write("    " + f.cType() + " " + f.name() + ";\n");
                    }
                    w.write("} " + s.cTypeName() + ";\n\n");
                } else if (layout instanceof Layout.FunctionPointer fp) {
                    w.write("typedef " + fp.cReturnType() + " (*" + fp.typedefName() + ")("
                            + String.join(", ", fp.paramCTypes()) + ");\n\n");
                }
            }
            w.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
            for (String prototype : prototypes) {
                w.write(prototype);
                w.write('\n');
            }
            w.write("\n#ifdef __cplusplus\n}\n#endif\n");
        }
    }

    private static Kind requireVetted(Kind kind, Class<?> owner, Set<Class<?>> vettedKindClasses) {
        if (!(kind instanceof Enum<?> constant)) {
            throw new IllegalStateException("Kind " + kind + " used by " + owner.getName()
                    + " is not an enum constant -- @NativeKindSet only vets Kind-implementing enums");
        }
        // getDeclaringClass(), not getClass(): a constant with its own class body
        // (an anonymous subclass) still reports the enclosing enum here, which is
        // what @NativeKindSet actually marks.
        Class<?> enumType = constant.getDeclaringClass();
        if (!vettedKindClasses.contains(enumType)) {
            throw new IllegalStateException(
                    "Kind " + kind + " (from " + enumType.getName() + ") used by " + owner.getName()
                            + " is not @NativeKindSet-annotated -- un-vetted Kinds can't be generated into a header");
        }
        return kind;
    }

    private static void collectNamedType(Kind kind, Set<Layout> namedTypes) {
        if (kind.cLayout() instanceof Layout.Struct || kind.cLayout() instanceof Layout.FunctionPointer) {
            namedTypes.add(kind.cLayout());
        }
    }

    private static String cType(Kind kind) {
        Layout layout = kind.cLayout();
        if (layout instanceof Layout.Primitive p) {
            return p.cType();
        }
        if (layout instanceof Layout.Struct s) {
            return s.cTypeName() + "*";
        }
        if (layout instanceof Layout.FunctionPointer fp) {
            return fp.typedefName();
        }
        throw new IllegalStateException("Unknown Layout subtype: " + layout);
    }
}
